### PR TITLE
Added HA vCenter deploy script

### PR DESCRIPTION
**Pull request by sammcgeown**
Added a script to deploy vCenter in HA mode using the advanced options.

### CODE REVIEW

**Comment by nickveldrin** [comment]
One request - it's currently set up to only work on a dvswitch deploy, so having an option here would be helpful. A thought, maybe adding a "standardswitch": true/false in the active part of the json config, then another variable to capture the standard switch vswitch#, and the portgroup.

You could easily just do a quick if standardswitch = true, then do it via those cmdlets, else use the existing dvswitch code in place. I wrote it this morning at work, but dont want to log in now to get it. I'll post it in the morning if anyone wants to see, but it's incredibly simple.

**Comment by nickveldrin** [comment]
I need to do some more research on Git to figure this all out, but i've made the code changes from a fork of Sam's script here - https://github.com/nickveldrin/HA-vCenter-Deploy

Can that be merged in? Or what would the process be for that?

**Comment by kmruddy** [comment]
Code looks good, merging. 

@nickveldrin you can fork this repo (vmware/PowerCLI-Example-Scripts), update the script within your fork, then create a PR.
Another option, once this has been merged, is to directly edit the script to involve your code and then create a new pull request.

**Comment by nickveldrin** [comment]
@kmruddy - appreciate the info! I want to add in one more thing into my repo before i do a pull request.  I wrote little batch files to kick off each stage of the powershell individually, so that you can do things at your own pace, and also it helps to monitor for problems.  I'll push these up later and submit the PR.

**Pull request merged**
