### PR TITLE
Push-vLIMessage

### PR DESCRIPTION
**Pull request by mycloudrevolution**
Push Messages to VMware vRealize Log Insight via API.

### CODE REVIEW

**Comment by mycloudrevolution** [comment]
I admit its no PowerCLI Script but its the API of a VMware Product...

**Comment by lucdekens** [comment]
Nice one.
Afaik Invoke-RestMethod was introduced in PowerShell v3, so I think the #Requires needs to be updated.

**Comment by mycloudrevolution** [comment]
I am not sure when it was introduced, but I definitely trust you! Is updated…

**Comment by lucdekens** [comment]
Approved for publication

**Comment by alanrenouf** [comment]
Nice work, love seeing Log Insight stuff here! keep it coming.

Approved by me, that makes 2 and a merge!

**Pull request merged**
