### PR TITLE
Adding several vSphere 6.5 API examples

### PR DESCRIPTION
**Pull request by lamw**
Contributing the following samples:

- AutomaticVMFSUnmap.ps1
- ESXInstallDate.ps1
- ESXInstalledVIBs.ps1
- SecureBoot.ps1
- vSphereLogins.ps1

### CODE REVIEW

**Comment by kmruddy** [comment]
Used PowerCLI 6.5 R1 on a vSphere 6.5 environment. 

AutomaticVMFSUnmap.ps1 - get-vmfsunmap appears to be missing the line declaring the $datastoreInfo variable and isn't working

Everything else looks good and operates as indicated in the comments.

**Comment by lamw** [comment]
Thanks for the catch @kmruddy Sample has been fixed

**Comment by kmruddy** [comment]
Looks good, approved. 

Need one more approval from the board members.

**Comment by alanrenouf** [comment]
+1 from me, looks good!

**Pull request merged**
