### PR TITLE
VM-CdDrive-Report

### PR DESCRIPTION
**Pull request by aaronwsmith**
1.0 PowerActions report script for Cluster objects.  Reports on status
of all VM's CD-Drives, making it easy to find VMs connected to a given
ISO or that might be using a physical ESXI host drive and unable to
vMotion.

### CODE REVIEW

**Comment by lucdekens** [comment]
Got my approval

**Comment by alanrenouf** [comment]
I would add some more metadata options to this as when its copied into the shared area it needs this to display correctly, specifically:

<#
.MYNGC_REPORT
.LABEL
Sample Example Script
.DESCRIPTION
Example script to use as template.
#>

Also see page 13 of the PowerActions Docs (https://labs.vmware.com/flings/poweractions-for-vsphere-web-client), it says to use a KEY so the right click menu item gets associated correctly, in this case VM.

**Comment by aaronwsmith** [comment]
Thanks for the feedback.  I'll incorporate the metadata options and then hopefully it's ready for a merge.

**Comment by aaronwsmith** [comment]
Question -- When I try to specify KEY(VM), PowerActions throws an error in the script editor: "An unexpected error has occurred: Unable to retrieve validation result."  Here is my current script header:

<#
.MYNGC_REPORT
KEY(VM)
.LABEL
VM CD-Drive Report
.DESCRIPTION
PowerActions Report Script that reports on VMs CD-Drive configuration, making it easy to find VMs holding onto ISOs that you 
need to update, or VMs that can't vMotion because they are tied into a physical resource from the ESXi host that is running it.
VM object is key (as it's the first managed object in the output), enabling you the ability to right-click an entry in the 
report to edit the target VM.  Script is able to report on VMs with multiple CD-Drives as well.  Version 1.0, written by
Aaron Smith (@awsmith99), published 07/29/2016.
#>

**Comment by aaronwsmith** [comment]
FYI - When I exclude "KEY(VM)" the script validates.  With how I wrote the script anyhow, the VM column seems to be defaulting a key, as I can right-click on any object in the report and get context menu options specific to that VM in question.  So not sure how to properly use the KEY() attribute.  Please advise.  Thanks!

**Comment by aaronwsmith** [comment]
Okay I figured out what worked ... I had to escape the parentheses for KEY().  Basically this:

KEY\(VM\)

I suspect the validation was failing in the Web Client because it didn't automatically escape these special characters before sending to the PowerActions server.  Web client log simply had this error every time I tried without explicitly escaping those characters:

com.vmware.vise.data.mutation.impl.MutationServiceImpl            MutationServiceImpl.validate failed: java.lang.reflect.InvocationTargetException: null

I'll make a final update to this pull request.  Hoping this gets what you're looking for Alan to do the merge.  Thanks!

**Comment by alanrenouf** [comment]
Awesome work, sorry for the delay in getting back but looks like you solved it. Nice stuff.  I approve, thats 2, time for a merge!

**Comment by aaronwsmith** [comment]
No problem Alan!  And sweet!  Happy to have the first merge in PowerActions!  Thanks!

**Pull request merged**
