### PR TITLE
Vi-Module manifest

### PR DESCRIPTION
**Pull request by rgel**
The Vi-Module module manifest PSD1 file

### CODE REVIEW

**Comment by lucdekens** [comment]
Thanks for contributing, impressive set of useful functions.
I think I tested most of functionality, and it looks good.

Some minor comments:
- PS style advises to not have plural forms of parameters (i.e. not -VMs but -VM, not DifferenceVMHosts, but DifferenceVMHost...)
- when testing an object type I would rather use the -is operator instead of the GetType() function
  Ex: $dev -is [VMware.Vim.VirtualDisk]
- Some functions have parameters that have the non-portable type, i.e. with Impl instead of Types (Enable-VMHostSSH, Disable-VMHostSSH)
- Get-VMHostFirmwareVersion: although still accepted in PS v4, I would not use a Filter anymore, but use a function. With a pipeline parameter that shouldn't be too hard.
- Some examples were written when the function was still a separate script, i.e. Find-VcVm

**Comment by rgel** [comment]
Hi Luc,

First of all, I am glad that it was you who checked my work.

I learned PowerCLI on your book (PowerCLI Reference yet first edition).

Would you like I will fix all these issues or you will accept the Module as is ?

Why you are not accept Filters, I learned this technique from your book (Get-FolderPath) ??? I think this is great and conveniently.

I just do not understand the last paragraph about Find-VcVm, can you please explain a bit more ?

 

Thank you very much.

**Comment by lucdekens** [comment]
Thanks, glad to hear that.

On the corrections, yes, please. I think that was the general idea that fixes would be introduced before we make the code public.
But perhaps wait till a second admin has validated the code.

Don't get me wrong, I have nothing against Filters.
"A Filter is just like a Function, but with only a Process block" after all :-) But I think that many users are less familiar with a Filter than they are with a Function. But no problem leaving it as a Filter.

The FindVcVm Help examples refer to .\Find-VcVm.ps, not Find-VcVm as a function.

**Comment by rgel** [comment]
Hi Luc,

I have fixed all your remarks.

Please review.

Thanks

**Comment by lucdekens** [comment]
Thanks.
For me the module is good to go.

**Comment by rynardtspies** [comment]
Sorry about the delay. I was on leave. 

I've downloaded the code and tested most of the functionality. I see no issues. 

Code looks good.

Approved.

**Comment by rgel** [comment]
Hi Rynardt and Luc,

Thank you both for the checking.

What the next step to merge the module to the repo ?

**Comment by lucdekens** [comment]
Well, as the main page on this repo states, when two board members "accept" the code, it can be merged.
Which is what I'll do :-)

**Comment by rgel** [comment]
Thank you Luc,

I have created one more pull request for README.md file.

Can you please review it?

**Pull request merged**
