### PR TITLE
Horizon Provisioning

### PR DESCRIPTION
**Pull request by praveenmathamsetty**
Horizon API Advanced functions for Horizon Connection Server (VSM@CLN 4610015)

### CODE REVIEW

**Comment by hrobinson1329** [comment]
Praveen,

Congratulations on this contribution for Horizon Advanced Functions.  Looking forward to comments from the community.  Try them, you will like them.

**Comment by praveenmathamsetty** [comment]
Thanks Henry, I will work on them

**Comment by kmruddy** [comment]
Initial review: 
**get-hvpool**
I would expect output to be similar to (get-hvpool).DesktopSummaryData

**new-hvpool**
Example text is not displaying properly within PowerShell

Example: 
-------------------------- EXAMPLE 7 --------------------------

C:\PS>Create new unmanaged manual pool from unmanaged VirtualMachines.


New-HVPool -MANUAL -PoolName 'unmangedVMWare' -PoolDisplayName 'unMngPl' -Description 'unmanaged Manual Pool
creation' -UserAssignment FLOATING -Source UNMANAGED -VM 'myphysicalmachine.vmware.com'

**get-hvevent**
I would expect the output to be (get-hvevents).Events

**start-hvfarm (and start-vmpool)**
examples are missing details
I would not expect to see start/stop parameters. 
I would expect start-hvfarm to perform: start-hvfarm -start
I would expect there to be a ‘stop-hvfarm’ function as well
I would also expect the enable/disable parameters be part of the set-hvfarm function

**start-hvpool**
Example 3 had a typo for the rebalance parameter

I'm still working on setting up my environment to test some of the other things, but the functionality is great so far! Huge step in the right direction!

**Comment by praveenmathamsetty** [comment]
Thanks Kyle, will work on this Initial review comments.

**Comment by hrobinson1329** [comment]
On Your Comment on start-hvfarm and start-hvpool

For the comment on start-hvfarm and start-hvpool would an alternative be to rename the verb to control-hvfarm and control-hvpool.

We are trying to avoid having a whole lot of verbs for pool management.
Is that a good alternative?

On your comment on get-hvpool output.

In general, we are still PowerShell newbies.  My question is on the object returned, vs the print output.

Surely want to make sure that we can retrieve the id of the object:
$obj=get-hvpool
$obj2.gettype()
$obj=(get-hvpool).desktopsummarydata
$obj2.gettype()

Question is whether we can influence what is displayed when you do a get-hvpool vs the object that is returned if you assign it to a variable.

Make sense?

henry

Henry Robinson
Sr. Director, Product Management, Horizon Platforms
VMware, Inc
(650) 906-2620

**Comment by kmruddy** [comment]
Regarding the use of verbs, I completely agree. Those should be as limited as possible. Personally, I would look at moving those over to the Set-HVPool/Farm functions. 

Also probably worth noting the approved verbs for use with PowerShell functions: https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx 
Otherwise you get a nasty error when importing the module. 

Regarding the output of get-hvpool, you can certainly change what's displayed by default. Check out the PowerShell formatting file: https://msdn.microsoft.com/en-us/library/gg580944(v=vs.85).aspx

**Comment by alanrenouf** [comment]
I had a chance to check out the modules tonight, adding to Kyles feedback, maybe these would have been better being added in smaller chucks so the feedback could be easily consumed and implemented? Just a thought as 4700+ lines of code takes a while to review ;)

Personally I dont like the underscore names of the interally used functions, this doesnt show powershell good practice to others reading the script to learn. I would use verb-noun for all functions, internal and external.

All these JSON files are super complicated, when you are trying to work out how these advanced functions work you end up jumping all around the place from advanced function to internal function to JSON file and back just to work out how this is being done, these should be example code and therefore easy to follow for others to work out how to create their own functions.  Maybe start smaller and allow for them to be built on than this complicated layout

1. Not sure I like the -Full parameter on the Get-HVFarm and Get-HVPool cmdlet, I would use 2 cmdlets here where Get-HV* gets all details and Get-HV*Summary returns the summary data?
2. New-HVFarm should take a PowerCLI folder (get-folder) as a VMFolder input here, not a string as how do you define the path of the folder?
3. Really dont like the spec options on the functions that give a JSON file, this is not like anything I have seen done in PowerShell before, i would rather see the JSON data in the function
4. -HostOrCluster takes a string and not a host or cluster powercli object?
5. - Datastores doesnt take a datastore powercli object?
6. Start-HVFarm/HVPool should not have a -Stop, -Enable, -Disable parameter, this should be a Stop-HVFarm, Enable-HVFarm, Disable-HVFarm function as this is not good PowerShell
7. Get-Machines should be singular, dont use plural function names.

**Comment by praveenmathamsetty** [comment]
-     Not sure I like the -Full parameter on the Get-HVFarm and Get-HVPool cmdlet, I would use 2  cmdlets here where Get-HV* gets all details and Get-HV*Summary returns the summary data?
[Praveen] : @alanrenouf  it seems then two Get-HVFarm and Get-HVPool cmdlets will become 4 cmdlets Get-HVFarm, Get-HVFarmView,   Get-HVPool  and Get-HVDesktopSummaryView? 
@hrobinson1329  is it fine

-     New-HVFarm should take a PowerCLI folder (get-folder) as a VMFolder input here, not a string as how do you define the path of the folder?
[Praveen] : @alanrenouf  get-folder is vSphere cmdlet, instead of that we can use VMFolder path as input. So that we use View API service method VmFolder_GetVmFolderTree and we can filter the VMFolder based on vmfolder path/name
-     Really dont like the spec options on the functions that give a JSON file, this is not like anything I have seen done in PowerShell before, i would rather see the JSON data in the function
@hrobinson1329  need your inputs here
-     HostOrCluster takes a string and not a host or cluster powercli object?
[Praveen] : @alanrenouf  this is also same as VMfolder, we have a view API service and uses HostOrCluster string to filter
-     Datastores doesnt take a datastore powercli object?
[Praveen] : @alanrenouf we need view API Ids. so that, we use View API service and filter the view API objects based on datastore  name
-     Start-HVFarm/HVPool should not have a -Stop, -Enable, -Disable parameter, this should be a Stop-HVFarm, Enable-HVFarm, Disable-HVFarm function as this is not good PowerShell
[Praveen] : @alanrenouf  I will modify this, could i move these functionalities to set-hvpool/set-hvfarm?
@hrobinson1329 need your inputs here
-     Get-Machines should be singular, dont use plural function names.
[Praveen] : @alanrenouf  I will modify this.

**Comment by hrobinson1329** [comment]
Henry Robinson
Sr. Director, Product Management, Horizon Platforms
VMware, Inc
(650) 906-2620

**Comment by alanrenouf** [comment]
Comments below:

·         Not sure I like the -Full parameter on the Get-HVFarm and Get-HVPool cmdlet, I would use 2  cmdlets here where Get-HV* gets all details and Get-HV*Summary returns the summary data?

[Praveen] : @alanrenouf it seems then two Get-HVFarm and Get-HVPool cmdlets will become 4 cmdlets Get-HVFarm, Get-HVFarmView, Get-HVPool and Get-HVDesktopSummaryView?

@hrobinson1329 is it fine

[Henry]  How about:

            Get-HvFarmSummary and Get-HVFarm
            Get-HVPoolSummary and Get-HVPool
            Get-HVMachineSummary and Get-HVMachine

Either Get-HVPoolSummary or Get-HVPool can be used in pipeline (get-hvpool –poolname xxx | new-pool or

Get-hvpoolsummary –poolname xxx | new-pool

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 Yes I like what Henry suggested!
`
·         New-HVFarm should take a PowerCLI folder (get-folder) as a VMFolder input here, not a string as how do you define the path of the folder?

  *

[Praveen] : @alanrenouf get-folder is vSphere cmdlet, instead of that we can use VMFolder path as input. So that we use View API service method VmFolder_GetVmFolderTree and we can filter the VMFolder based on vmfolder path/name

[Henry] @alanrenouf Is it ok to use vSphere cmdlets as a pre-requisite.  Be good to understand the guidelines here.  Praveen, it would be better to use vSphere commands as the user would be generating the folders using vSphere.

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 taking a string or a folder here would be great and would cover the connection issues mentioned where the user may not be connected to vCenter as well.`

·         Really dont like the spec options on the functions that give a JSON file, this is not like anything I have seen done in PowerShell before, i would rather see the JSON data in the function

  *

@hrobinson1329  need your inputs here

[Henry] @alanrenouf … The JSON file for Horizon is rather complex.  There are good reasons to have it as a file because people would manipulate as a specification that they would like to preserve/copy/change through the process.  Not too many examples of complex JSON that I have found in PS.

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 The PowervRA guys do a great job of this here: https://github.com/jakkulabs/PowervRA/tree/development/PowervRA/Functions/Public`


·         HostOrCluster takes a string and not a host or cluster powercli object?

  *

[Praveen] : @alanrenouf this is also same as VMfolder, we have a view API service and uses HostOrCluster string to filter

[Henry] same comment as VMFolder.

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 taking a string or a cluster or host object here would be great and would cover the connection issues mentioned where the user may not be connected to vCenter as well.`

·         Datastores doesnt take a datastore powercli object?

  *

[Praveen] : @alanrenouf we need view API Ids. so that, we use View API service and filter the view API objects based on datastore name

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 taking a string or a datastore object here would be great and would cover the connection issues mentioned where the user may not be connected to vCenter as well.`

·         Start-HVFarm/HVPool should not have a -Stop, -Enable, -Disable parameter, this should be a Stop-HVFarm, Enable-HVFarm, Disable-HVFarm function as this is not good PowerShell

  *

[Praveen] : @alanrenouf I will modify this, could i move these functionalities to set-hvpool/set-hvfarm?
@hrobinson1329  need your inputs here

[Henry] Yes, I believe that changing to set-hvpool and set-hvfarm is the right approach here.

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 Sounds great!`

·         Get-Machines should be singular, dont use plural function names.

[Praveen] : @alanrenouf I will modify this.

Shouldn’t this be get-hvmachine(?)

`[alanrenouf comment] @praveenmathamsetty & @hrobinson1329 Yeah Get-HVMachine`

**Comment by hrobinson1329** [comment]
Can you give us a link of the prototype call that you think we should emulate?

Thanks much,

Henry

Henry Robinson
Sr. Director, Product Management, Horizon Platforms
VMware, Inc
(650) 906-2620

**Comment by alanrenouf** [comment]
This one looks fairly small... https://github.com/jakkulabs/PowervRA/blob/development/PowervRA/Functions/Public/New-vRATenant.psm1

**Comment by hrobinson1329** [comment]
Thanks.  My only concern is whether PS has any restrictions on the size of the command line and/or needing to put continuation characters in the file.  Our JSON is about 3-5K and much larger than the example that you provided.

Henry

Henry Robinson
Sr. Director, Product Management, Horizon Platforms
VMware, Inc
(650) 906-2620

**Comment by hrobinson1329** [comment]
Here is the problem that we are trying to solve:

Get-hvpool returns the DesktopSummaryView object.

Of course, this object contains two objects: desktopID and desktopsummarydata and so the standard output just shows the two objects.  (boring)

What we would like to do is make sure to return DesktopSummaryView  (so that user can get the id) but format the output so that the contents of the desktopsummarydata is displayed.  Tried to fool around with the formatting file but not sure how to specify the embedded property of an object (i.e desktopsummarydata.name) in the output to be displayed.

Make sense?

Henry
Henry Robinson
Sr. Director, Product Management, Horizon Platforms
VMware, Inc
(650) 906-2620

**Comment by kmruddy** [comment]
Due to an update in the approval policy (https://github.com/vmware/PowerCLI-Example-Scripts#approval-of-additions), this pull request has been committed. Please use this repo’s Issues section for any additional comments.

Thanks!

**Pull request merged**
