### PR TITLE
VM-Snapshot-Report.ps1, Version 1.0

### PR DESCRIPTION
**Pull request by aaronwsmith**
Ready for merge if accepted.  PowerActions Report Script that reports on
VMs with snapshots along with their description, size of the snapshot in
GB, the VM's provisioned vs. used space in GB,
if the snapshot is the
current one being used, its parent snapshot (if there is one), and the
Power state of the VM itself. VM object is key (as it's the first
managed object in the output), enabling you the ability to right-click
an entry in the report to edit the target VM.

### CODE REVIEW

**Comment by aaronwsmith** [comment]
Added fields to report for the date the snapshot was created + calculated age in days for the snapshot.

**Comment by kmruddy** [comment]
Tested against VCSA 6.0, PCLI 6.0, PowerActions 1.5

Report works properly.  Approved.

**Comment by aaronwsmith** [comment]
Thanks!  Ready to merge then? :-)

**Comment by kmruddy** [comment]
Still need one more person to test, then we're good!

**Comment by aaronwsmith** [comment]
Zzzzz...  :-)

**Comment by kmruddy** [comment]
Due to an update in the approval policy (https://github.com/vmware/PowerCLI-Example-Scripts#approval-of-additions), this pull request has been committed. Please use this repo’s Issues section for any additional comments.

Thanks!

**Pull request merged**
