### PR TITLE
New VMware.Hv.Helper functions

### PR DESCRIPTION
**Pull request by freythman**
Get-HVvCenterServer
Get-HVvCenterServerHealth
Get-HVBaseImageVM
Get-HVBaseImageSnapshot

### CODE REVIEW

**Comment by kmruddy** [comment]
Looks like the last commit caused a conflict with this PR. Can you resolve?

**Comment by freythman** [comment]
Fixed now.

**Comment by amikkelsendk** [comment]
Thanks matt

Best Regards
Anders Mikkelsen

**Comment by Magneet** [comment]
the virtualcenter health was already included with the get-hvhealth command

**Comment by freythman** [comment]
I see that now. I will remove it in the next PR

**Pull request merged**
