### PR TITLE
Add VMHost SSH management scripts

### PR DESCRIPTION
**Pull request by pjorg**
Add scripts for enabling and disabling the TSM-SSH service on ESXi
hosts.

### CODE REVIEW

**Comment by alanrenouf** [comment]
Just wondering why you didn't use the start-vmhostservice here?

**Comment by pjorg** [comment]
In my experience, and with the environments I work in, there is a very significant speed difference between calling `Get-VMHostService` and then piping to `Start-VMHostService` for each host, versus this `ExtensionData` call. 

In fairness, the performance gap seems to have closed a bit in more recent versions of vSphere and PowerCLI.

**Comment by alanrenouf** [comment]
Fair enough, I guess you have hundreds of hosts ;)

**Comment by pjorg** [comment]
Speed speed speed! It would be so much better if `Get-VMHostService` had a `-Name` flag so you didn't have to pull all the services and filter at the client side.

And yes, I do have 100 hosts. ;-) Thanks for merging!

**Pull request merged**
