### PR TITLE
Get-VMotion

### PR DESCRIPTION
**Pull request by brianbunke**
Retrieve s/vMotion event history. (and small updates to my existing Get-DatastoreProvisioned files)

Side note: Writing the tests file for this is killing me. I am having trouble mocking Get-View properly to apply to its use within Get-VMotion, and/or I don't know how to proxy custom object type "VMware.VimAutomation.Sdk.Types.V1.VIObject[]" properly. Any help appreciated :)

### CODE REVIEW

**Comment by lucdekens** [comment]
Afaik, the events VmBeingHotMigratedEvent and VmBeingMigratedEvent are not needed. These indicate that the vMotion started. See also my my [Get the vMotion/svMotion history](http://www.lucd.info/2013/03/31/get-the-vmotionsvmotion-history/) post.

**Comment by brianbunke** [comment]
Hmm, in that case, looks like I may be wasting time on a solved problem. Maybe I can scare up some performance improvements? Or maybe I should urge you to upload your script and spend time on a different problem that would be more useful to the community :)

**Comment by lucdekens** [comment]
No, no, please submit your scripts and functions.
All contributions are more than welcome.

**Comment by brianbunke** [comment]
The use case for keeping all four event types is returning the duration, by calculating from start and end times. Not the world's most important property, but I've been curious about specific VMs once or twice.

I can still trim it down if preferred, but I don't think they're completely unnecessary?

After reviewing your post (...why didn't I look harder before I started...), I'm interested in rolling in some of that functionality too, because there's some slick extra options. But it'll have to wait for another time.

**Comment by alanrenouf** [comment]
I agree, make sure you still commit it, very valid. Perhaps update this commit with the changes you make from Lucs?

**Comment by brianbunke** [comment]
Overhauled this, and am pretty happy with the feature set and performance at this point. Kept the "start" events to calculate duration. Take a look and let me know what you think. Thanks!

**Comment by lucdekens** [comment]
Just tested, works perfect.

One (somewhat) major comment:
- the Entity parameter type you use is not future-proof. See http://blogs.vmware.com/PowerCLI/2016/04/powercli-best-practice-correct-use-strong-typing.html

Some minor comments (and I know I'm nitpicking):
- Entity parameter: I know the comment states Datacenter, Cluster and VM, but I can enter whatever other item, and get an error. Perhaps add a parameter ValidateScript?
- Days, Hours and Minutes accept negative values. Although I understand the script is not clairvoyant, perhaps add a parameter validation ([ValidateRange(0,[int]::MaxValue)])

One improvement suggestion:
- Perhaps add a Server parameter? For those users with multiple vSphere connections, now it goes for the $global:defaultviserver

**Comment by rynardtspies** [comment]
Tested. Works well. Nice work.

I'm happy with the code to be committed. Might be worth changing the code to future-proof the entity param as Luc mentioned.

**Comment by brianbunke** [comment]
I appreciate the review and the nitpicking. I got really deep in the weeds during testing, and completely forgot about validating the parameters. Will implement all the suggestions today.

**Comment by brianbunke** [comment]
Changes made, hopefully all in line with best practices. Good to know going forward!

**Comment by lucdekens** [comment]
Just tested the new code. 
I suspect you forgot to include the code to handle multiple vSphere Server connections.

When I pass two or more vCenters for example, nothing is returned.
The reason being that the Get-View EventManager will return an array.

Same happens when I'm connected to multiple servers and don't pass anything on the Server parameter and I have DefaultVIServerMode set to Multiple.

Sorry to keep bothering you about this :-(

**Comment by brianbunke** [comment]
Just to comment since this has been stale for a week:

That's accurate, the `Server` param needs more work. I don't have a testing area with multiple vCenters. Hoping I can set one up soon to make this happen.

**Comment by brianbunke** [comment]
I'm back for more. Hit me with your best shot :wink: 

Chose to copy the Get-VM/Get-Cluster behavior of defaulting to Servers instead of Server. I'm not aware of whether there's a specified best practice regarding -Server parameter implementation.

Thanks for all the free feedback!

**Comment by alanrenouf** [comment]
@brianbunke Awesome work however, Just tried this and dont get an entry, I did from @lucdekens script though?!

 ```
Get-MotionHistory -Entity (get-VM) -days 1


CreatedTime  : 11/10/2016 11:59:18 PM
Type         : vMotion
UserName     : VSPHERE.LOCAL\Administrator
VM           : New Virtual Machine
SrcVMHost    : 10
TgtVMHost    : 10
SrcDatastore : NFS01
TgtDatastore : 




 C:\Users\renou_000> Get-VMotion -Entity (get-vm) -Days 1

 C:\Users\renou_000> 
```

**Comment by brianbunke** [comment]
Thanks, @alanrenouf, would you mind trying again? I just submitted a bug fix that addresses behavior when the user has multiple vCenter server connections open.

If you didn't have multiple connections open, both scripts behave the same for me. If that's the case, maybe someone else can try replicating?

**Comment by alanrenouf** [comment]
Sorry, still doesnt work for me

**Comment by alanrenouf** [comment]
Also maybe remove the "#Requires -Version 3 -Modules VMware.VimAutomation.Core" as then this code will also work on PowerCLI Core (When it works ;)

**Comment by alanrenouf** [comment]
Was it something I said?

**Comment by brianbunke** [comment]
Unfortunately, I don't know what you're running into, and I'm afraid I can't dedicate the time to troubleshoot at this point.

**Comment by alanrenouf** [comment]
I understand, I will try and work out whats going on my end, dont want you to cancel this, its a great addition!

**Pull request closed without merging**
