### PR TITLE
Adding Remove-HVMachine function

### PR DESCRIPTION
**Pull request by jrodsguitar**
First commit. Please feel free to provide constructive criticism. 

This function removes/deleted a VM(s) from a pool. I tested a against full clone and linked clone pools. As an ongoing maintenance task, I intend to add even more functionality such as removal of manual pool desktops etc via a switch -manualPool or something similiar. 

I attempted to adhere to the repository standards as much as possible, and formatted the code for readability as much as I could. 

I've been recently contributing to the VMware communities page as well in case you are wondering what else I have to offer.

### CODE REVIEW

**Comment by Magneet** [comment]
please use the full where-object instead fo where and connect to the services like this:
+  $services = Get-ViewAPIService -hvServer $hvServer
     if ($null -eq $services) {
 	    Write-Error "Could not retrieve ViewApi services from connection object"
 	    break
 	  }`
and use $services instead of $hvapi I would also advise to look into the service helper command instead of using specs

**Comment by jrodsguitar** [comment]
Thank you Magneet. Per your suggestions I have now implemented the Get-ViewAPIService way of connecting. I have also standardized on using the $services variable.

I will have to look into using the helper service for delete machine method instead of spec as well. 

Thank you very much for the feedback.

**Comment by kmruddy** [comment]
Note: this PR has some conflicts at the moment.

**Comment by jrodsguitar** [comment]
Fixed conflicts.

**Comment by kmruddy** [comment]
Looks good, merging.

**Pull request merged**
