### PR TITLE
Create VMFSIncrease.psd1

### PR DESCRIPTION
**Pull request by lucdekens**
Added the VMFSIncrease module

### CODE REVIEW

**Comment by alanrenouf** [comment]
Now to create a way to test this ;) Not that I distrust it works.

**Comment by lucdekens** [comment]
I was thinking about adding some Pester tests.

Unit testing is quite straightforward, I can add some of those.
But how do you do Integration testing?
By definition it would be destructive, claiming free space on an extent, or
claiming a free LUN.

All the examples on the web are quite straightforward and simple; mocking a
value, and then seeing how the function handles it.

In fact I'm pondering the same question for my vSphereDSC resources module.

If anyone has a bright idea, I'll be more than happy to listen.

**Comment by brianbunke** [comment]
It seems like the only way to add a true integration test is to wrap New/Remove datastore operations around your New-VmfsDatastoreIncrease test. Essentially, spin up and tear down your small test environment. Which, of course, requires that you specify your unique storage location, and already have space provisioned for New-Datastore to execute successfully. Not easy, not impossible :)

**Comment by lucdekens** [comment]
Well, this Pull request is probably not the place to discuss this at length, but I do have a fundamental issue with the Testing.
In a good DevOps sense we want to have continous delivery, but when we transpose this to platform types of infrastructures (vs application where the TDD idea is a great concept), there are some fundamental differences.
While we can envisage setting up test input (heck we can even use a copy of real data) or mocking behaviour for documented interfaces for Application testing, all this becomes more complex (and impossible ?) when we move to Infrastructure.
The ideal situation would be to "test" (unit and infra) in a kind of greenfield. But that seems to be a costly solution imho.
So we go to testing in a "real" environment. But then our tests could have impact on other components, and that is a no-no in my book.
Did we just find a loophole in the DevOps concept when applied to infrastructure?
Probably not, but then SDDC becomes quite theoretical.

Ah, never mind, my Friday afternoon rant is over ;-)

**Comment by kmruddy** [comment]
Not sure if it's my lab (using a local disk) or what's going on but I'm hitting some snags. 

**get-vmfsdatastoreincrease** hits a couple issues: 
_C:\> Get-Datastore -Name temp | Get-VmfsDatastoreIncrease_

Error: 
_Cannot index into a null array.
At C:\...\Downloads\VMFSIncrease\VMFSIncrease.psm1:108 char:5
+                 $partMax = ($vmfsExpOpt[0].Info.Layout.Partition | where{ $_.Type -eq 'VMFS' ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\...\Downloads\VMFSIncrease\VMFSIncrease.psm1:114 char:74
+                     Model = "$($disk.Vendor.TrimEnd(' ')).$($disk.Model.TrimEnd(' ')).$($disk.R ...
+                                                                                         ~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray_

Line 108: I'm assuming the variable being referenced should be $vmfsExtOpt ?
Line 115: the second variable should be $partinfo and not $hdpartinfo (looks like you already found that issue based upon commits to your own repo)

**new-vmfsdatastoreincrease** hits a snag too: 
_C:\> Get-Datastore -Name temp | New-VmfsDatastoreIncrease -IncreaseSizeGB 15 -Expand_

Error: 
_Cannot index into a null array.
At C:\...\VMFSIncrease\VMFSIncrease.psm1:184 char:6
+                     $partMax = ($vmfsExpOpt[0].Info.Layout.Partition | where{ $_.Type -eq 'VMFS ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

New-VmfsDatastoreIncrease : Requested expand size 15GB not available on t10.ATA_____HITACHI_HUA721010KLA330_________________PBK5WERF____________
At line:1 char:28
+ Get-Datastore -Name temp | New-VmfsDatastoreIncrease -IncreaseSizeGB 15 -Expand
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-VmfsDatastoreIncrease_

I'm assuming it's because $vmfsExpOpt isn't defined within that function. If I add the following line between line 183 and 184 it works fine (pulled from the get-vmfsdatastoreincrease function): 
$vmfsExpOpt = $hdSys.QueryVmfsDatastoreExpandOptions($Datastore.ExtensionData.MoRef)

**Comment by lucdekens** [comment]
Thanks Kyle.
Line 108: the QueryVmfsDatastoreExtendOptions method seems to always return an array, hence my index 0.
Could it be that there is no Extend available.
If yes, I will have to add a failsafe when $null is returned.

Line 115: yes, already found that one as you noticed on my GitHub repository.
Blame it on my GitHub noob-ness (how is that GitHub expert-led training session coming along?)

Line 184: that is because I used $expOpt instead of $vmfsExpOpt in line 171.
I'll correct that one and test it before submitting.

Thanks for testing

**Comment by kmruddy** [comment]
Due to an update in the approval policy (https://github.com/vmware/PowerCLI-Example-Scripts#approval-of-additions), this pull request has been committed. Please use this repo’s Issues section for any additional comments.

Thanks!

**Pull request merged**
