### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by rgel**
Hi Luc,
Can you please approve the README.md file, it contains the links to the articles about every function and little help about module usage.

### CODE REVIEW

**Comment by lucdekens** [comment]
Nice, approved.

**Comment by rgel** [comment]
Thank you, will be waiting for a second member to approve …

**Comment by rynardtspies** [comment]
Approved :)

**Comment by rgel** [comment]
Thank you Luc

**Comment by rgel** [comment]
Hi Luc,

I had found one bug in my Vi-Module and had fixed it.

Can you please review and merge?

https://github.com/vmware/PowerCLI-Example-Scripts/pull/27/commits

Thanks in advance.

**Pull request merged**
