### PR TITLE
update VMware.VMEncryption for vSphere 6.7

### PR DESCRIPTION
**Pull request by simonfangyingzhang**
1 add new function Set-VMCryptoUnlock
2 deprecating functions related to KMServer and KMSCluster from VMware.VMEncryption
3 version from 1.0 to 1.1 and other minor changes

### CODE REVIEW

**Comment by BaoyinQiao** [comment]
Those changes looks good to me, wait for the group owner's approval.

**Comment by simonfangyingzhang** [comment]
@alanrenouf @kmruddy could you please take a look and approve it? thanks

**Comment by kmruddy** [comment]
Merging.

**Comment by simonfangyingzhang** [comment]
thanks Kyle and Baoyin

**Pull request merged**
