### PR TITLE
Updated Find-HVMachine

### PR DESCRIPTION
**Pull request by mtelvers**
Updated Find-HVMachine to use the iterative query service, QueryService_Create() rather than the quick QueryService_Query()

### CODE REVIEW

**Comment by kmruddy** [comment]
Like Mark, I don't have 1000+ desktops in my environment, but it looks solid. Merging.

**Comment by rpstester** [comment]
Since downloading and using this update, when I run `Get-HVMachine -State DELETING` using a state that doesn't have any desktops, then it does not return/finish, whereas before, it would respond with: 

> Get-HVMachineSummary: No machine(s) found with given search parameters

Get-HVMachineSummary is the same way.  Would you please correct this?

**Comment by mtelvers** [comment]
I've added a fix to PR #131

**Comment by rpstester** [comment]
Thank you, @mtelvers .  It is working again as expected!

**Pull request merged**
