### PR TITLE
Report-LUNPath-ESXCLI

### PR DESCRIPTION
**Pull request by mycloudrevolution**
This script will create a Report of LUNs with Paths that have more than one unique LUN ID or have more than the defined Paths. 

Information’s will be gathered via ESXCLI. This is necessary to report also hidden Paths!

### CODE REVIEW

**Comment by alanrenouf** [comment]
Looks good, approved!

**Comment by lucdekens** [comment]
Tested, works great.

Since the script is using the V2 switch on the Get-EsxCli cmdlet, I would like to see the requirement to minimally have PowerCLI 6.3 R1 mentioned somewhere. 
Something like this would probably be the best solution (even if the PCLI module autoloading doesn't work, it would at least check the version of the loaded PCLI module).

#Requires -Modules VMware.VimAutomation.Core, @{ModuleName="VMware.VimAutomation.Core";ModuleVersion="6.3.0.0"}

**Comment by mycloudrevolution** [comment]
OK, thanks for your hint!

I have added "#Requires " and some additional Notes.

**Comment by lucdekens** [comment]
Thanks; good to go for me

**Pull request merged**
