### PR TITLE
Fixes to Get-HVDatastore() when multiple datastores are specified

### PR DESCRIPTION
**Pull request by mtelvers**
`$Datastores` needs to be initialized as an empty array `@()` rather than `$null`.  Furthermore, if `$DsStroageOvercommit` is empty it is only initialised with a single element where there should be one element per datastore.  I've moved the test into the loop instead.

### CODE REVIEW

**Comment by maniaX1** [comment]
I will test it on Monday and let you know. Anyway thanks for now!

**Comment by kmruddy** [comment]
Don't have an environment to test, but looks good!

**Comment by pythongitram** [comment]
I have tried   to  use this command set-hvpool with key and value pair ..I am getting the below error  . Could you please help me on this? I have imported the latest vmwarehvhelper module.

Exception calling "Desktop_Update" with "3" argument(s): "ExceptionType : VMware.Hv.InvalidArgument
ErrorMessage : Invalid member name.
ParameterName : DesktopSettings.DisplayProtocolSettings.EnableHTMLAccess"
At C:\Program Files\WindowsPowerShell\Modules\VMware.Hv.Helper\VMware.HV.Helper.psm1:6183 char:8
+        $desktop_helper.Desktop_Update($services,$item,$updates)
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : VimException

**Comment by mtelvers** [comment]
Hi, the key values are case sensitive.  Try

     Set-HVPool -PoolName YourPool -Key "desktopSettings.displayProtocolSettings.enableHTMLAccess" -Value $true

Also you can use `Set-HVPool -enabledHTMLAccess $true` to avoid the problem.

**Comment by pythongitram** [comment]
how do I know the exact case for the settings?


Thanks,
Ramdas R

**Comment by mtelvers** [comment]
Hi Ramdas, I use the API reference at [https://code.vmware.com/apis/75/view](https://code.vmware.com/apis/75/view).  Choose All Properties from the menu on the left and enter the property in the search box.

Mark

**Pull request merged**
